### ISSUE TITLE
merge failing

### ISSUE THREAD

**Issue by saucam** [Leeroo-AI/mergoo#7]
Hi,

I was trying to run the library to create moe model, but it failed with below error

```
 73%|███████▎  | 213/291 [00:10<00:02, 26.58it/s]
 74%|███████▍  | 216/291 [00:10<00:03, 24.48it/s]
 76%|███████▋  | 222/291 [00:10<00:02, 29.15it/s]
 78%|███████▊  | 226/291 [00:10<00:02, 29.59it/s]
 79%|███████▉  | 231/291 [00:11<00:02, 29.63it/s]
 81%|████████  | 235/291 [00:11<00:01, 30.09it/s]
 82%|████████▏ | 239/291 [00:11<00:01, 31.32it/s]
 84%|████████▎ | 243/291 [00:11<00:01, 26.91it/s]
 86%|████████▌ | 249/291 [00:11<00:01, 26.08it/s]
 87%|████████▋ | 252/291 [00:12<00:01, 22.32it/s]
 88%|████████▊ | 255/291 [00:12<00:01, 22.68it/s]
 89%|████████▊ | 258/291 [00:12<00:01, 21.02it/s]
 90%|████████▉ | 261/291 [00:12<00:01, 21.32it/s]
 91%|█████████▏| 266/291 [00:12<00:00, 26.88it/s]
 92%|█████████▏| 269/291 [00:12<00:01, 20.41it/s]
 93%|█████████▎| 271/291 [00:12<00:00, 21.12it/s]
2024-04-26T17:45:14.505943319Z Traceback (most recent call last):
2024-04-26T17:45:14.505957629Z   File "/mergoo/mergoo/composers/composer_moe.py", line 138, in compose
2024-04-26T17:45:14.505976029Z model.layers.30.self_attn.q_proj.weight tensor(..., device='meta', size=(4096, 4096), dtype=torch.float16)
2024-04-26T17:45:14.506356869Z     self.state_dict[layer_name] = prev_weight + (param / n).to(
2024-04-26T17:45:14.506368820Z NotImplementedError: Cannot copy out of meta tensor; no data!
2024-04-26T17:45:14.506372829Z 
2024-04-26T17:45:14.506375800Z During handling of the above exception, another exception occurred:
2024-04-26T17:45:14.506379169Z 
2024-04-26T17:45:14.506381809Z Traceback (most recent call last):
2024-04-26T17:45:14.506384929Z   File "/training/mergoo/merge.py", line 43, in <module>
2024-04-26T17:45:14.506422789Z     expertmerger.compose()
2024-04-26T17:45:14.506429789Z   File "/mergoo/mergoo/composers/composer_moe.py", line 143, in compose
2024-04-26T17:45:14.506463129Z     self.state_dict[layer_name] = param.to("cpu")
2024-04-26T17:45:14.506466449Z NotImplementedError: Cannot copy out of meta tensor; no data!
```

Here is the config

```
{
    "model_type": "llama",
    "num_experts_per_tok": 2,
    "experts":[
        {
            "expert_name" : "base_expert",
            "model_id" : "meta-llama/Meta-Llama-3-8B"
        },
        {
            "expert_name" : "expert_1",
            "model_id" : "cognitivecomputations/dolphin-2.9-llama3-8b"
        },
        {
            "expert_name" : "expert_2",
            "model_id" : "abacusai/Llama-3-Smaug-8B"
        },
        {
            "expert_name": "expert_3",
            "model_id": "McGill-NLP/Llama-3-8B-Web"
        },
        {
            "expert_name": "expert_4",
            "model_id": "openlynn/Llama-3-Soliloquy-8B"
        }
    ],
    "router_layers":[
        "gate_proj",
        "up_proj",
        "down_proj"
    ]
}
```

Could you please suggest what am I doing wrong? I used the latest source code.

**Comment by jacklanda** [comment]
I just got this error message the day before yesterday.

Could you provide the code you used to merge the LMs?

**Comment by alirezamshi** [comment]
Hi,

This error happened since part of your experts are not loaded into GPU device (due to limits of your GPU memory). By default when there is not enough memory, HF loads models in meta device (meaning no weights are loaded, but you can use the model architecture for your debugging purpose).

So, there are no weights loaded for merging.

I suggest to merge fewer experts according to your GPU memory limitation.

**Comment by saucam** [comment]
ok understood. Is it not possible to support merging models even if gpu memory is not enough but there is enough RAM?

**Comment by alirezamshi** [comment]
It's planned on the roadmap, but feel free to do a PR :)

**Comment by saucam** [comment]
thank you ! I would love to, but would need your guidance on how it can be done :)

**Comment by saucam** [comment]
@jacklanda I just followed the notebook here: https://github.com/Leeroo-AI/mergoo/blob/main/notebooks/integrate_llama3_experts.ipynb

**Comment by alirezamshi** [comment]
@saucam Sure, happy to help on that :)

**Comment by alirezamshi** [comment]
Closing this, feel free to open it ;)
